import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>e-commerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Hello World</h1>
      </main>

      <footer>
          <p>Todos os direitos reservados</p>
      </footer>
    </>
  );
};

export default Home;
