import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>e-commerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Hello World</h1>
      </main>

      <footer>
          <p>Todos os direitos reservados</p>
      </footer>
    </div>
  )
}

export default Home
